### ISSUE TITLE
Not AX.25 on Direwolf

### ISSUE THREAD

**Issue by YD0NXX** [phdlee/uvk5cec#11]
Hello, thanks for the work but on my UV-K5 is undecoded.

The APRS transmission is read as "(Not AX.25)" on my gateway running Direwolf 1.6.

I've followed the instruction on http://www.hamskey.com/, but I might miss one or another

By monitoring the TX audio on another radio, the sound level seems too hot, is there a menu to reduce the TX audio level?.

FW: 0.2B and 0.2C 

73 de Yono - YD0NXX

**Comment by tristanmoney** [comment]
My Direwolf I-gate works with my UV-K5(8). Do you have the correct APRS frequency programmed in channels 169 and 170? What kind of radio is Direwolf connected to?

**Comment by jangelor** [comment]
The "message" part is not yet APRS spec compliant (see my previous comment).

However, for positioning, be sure you have your destination and digipath set correctly.

DEST - set it to an experimental "Z" destination. I have set mine to APZQSH

DIGI - set it to your digipath setting without the second digit. For examaple WIDE1

digiSSID - set it to your digipath second digit, for example 1 ... with the above setting, this should make the digipath WIDE1-1

The packet should now be ax.25 frame. Hopefully Ian KD8CEC gets to release and update soon with better message implementation.

**Comment by jangelor** [comment]
BTW, aside from checking the direwolf logs, you can also get into KISS terminal (e.g., kissutil) to "listen" to what direwolf hears. If the packet is mis-formatted, you will see it there, too.

**Comment by YD0NXX** [comment]
> The "message" part is not yet APRS spec compliant (see my previous comment).
> 
> However, for positioning, be sure you have your destination and digipath set correctly.
> 
> DEST - set it to an experimental "Z" destination. I have set mine to APZQSH
> 
> DIGI - set it to your digipath setting without the second digit. For examaple WIDE1
> 
> digiSSID - set it to your digipath second digit, for example 1 ... with the above setting, this should make the digipath WIDE1-1
> 
> The packet should now be ax.25 frame. Hopefully Ian KD8CEC gets to release and update soon with better message implementation.

Thanks for the pointers, somehow on AprsDIG I use WIDE2-2 is the one that made as Not.AX25 packets.
So I follow your setting:
- AprsDIG: WIDE1
- digiID (menu 9) as 1
and now I'm decoded properly (as YD0NXX-9), but with wrong LAT and LON values (I use decimal degrees format).

Thanks for the great work,

73 de Yono YD0NXX

**Comment by YD0NXX** [comment]
Further test shows the GPS decimal degrees for LAT and LON should be 3 decimals only

**Comment by YD0NXX** [comment]
As the problem is already resolved, I'm going to close this issue.
