### ISSUE TITLE
GPS Coordinates are not  send ok to air.

### ISSUE THREAD

**Issue by mariano80** [phdlee/uvk5cec#27]
Hi ! First to thank the development of this firmware!

I have a problem with GPS coordinates. I loaded in the menu like the web site is described. Using the formating of Google. But when i saw the raw packets, coordinates are different and in the map my UV-K5 is shown in another country hehe.

![image](https://github.com/phdlee/uvk5cec/assets/26579010/75d529dc-546c-47e8-854b-4f3f9c367476)
![image](https://github.com/phdlee/uvk5cec/assets/26579010/31f9d50d-d498-46d9-b9a7-0ce3de3ed67c)

The APRS RAW Packet

2024-02-27 15:55:52 -03: LW2DHT-6>APK5C1,WIDE2,qAR,LU7AA-10:!3400.63S/05800.13WD
2024-02-27 15:59:38 -03: LW2DHT-6>APK5C1,WIDE2,qAR,LU7AA-10:!3400.62S/05800.23WD

Regards,
LW2DHT

**Comment by DL8LDN** [comment]
I have same problem. 73 de DL8LDN

**Comment by mariano80** [comment]
Ok, I test version 02.P and now 0.2R. The same problem in both.

**Comment by mariano80** [comment]
I tested in APRSdroid using AFSK audio and the same thing.

![image](https://github.com/phdlee/uvk5cec/assets/26579010/caa81a09-8742-4098-a49a-3b1db76f9393)

**Comment by 6h49af** [comment]
bad path, good coordinates.
I’m all OK.

> I tested in APRSdroid using AFSK audio and the same thing.
> 
> ![image](https://private-user-images.githubusercontent.com/26579010/308354239-caa81a09-8742-4098-a49a-3b1db76f9393.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwODAyOTIsIm5iZiI6MTcwOTA3OTk5MiwicGF0aCI6Ii8yNjU3OTAxMC8zMDgzNTQyMzktY2FhODFhMDktODc0Mi00MDk4LWE0OWEtM2IxZGI3NmY5MzkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDAwMjYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3YWE2YzU3NDFmMjc0YmNmZGMyNDkwZDNjYmZjOGJhMTQ0ZjQzOWU4ZGU1NTU0MmIyNmRhZTAwZmIxM2FkNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zq7De9q0HCOS6Vugiwq8hKZ5qnAfrhjb3bWmt6dwp7U)

**Comment by phdlee** [comment]
LW2DHT
When transmitting APRS, GPS coordinates are converted to the desired format
in APRS and transmitted.
I haven't calculated it, but it looks like it was transmitted properly?
I'll enter your coordinates and run a test sometime this week.
Ian KD8CEC

**Comment by phdlee** [comment]
DL8LDN
Thanks for testing

GPS coordinates are converted to APRS format and transmitted.
Send me your coordinates and I will test it.

Ian KD8CEC

**Comment by mariano80** [comment]
Hi Ian! Thanks for your answer. This is my test IGATE raw packet msg with the coordinates. The coordinates send by the Qsheng are ver far from reality, more than 100km.

2024-02-27 17:08:34 -03: LW2DHT-3>APE32I,WIDE1-1,qAS,LW2DHT-1:/272008z3435.36S/05832.91W#/A=000003 Test Mode - Only Inet
2024-02-27 17:18:34 -03: LW2DHT-3>APE32I,WIDE1-1,qAS,LW2DHT-1:/272018z3435.36S/05832.91W#/A=000003 Test Mode - Only Inet

Thanks again for your time! You have done and doing a great job with this. Very Appreciated,
Regards Mariano LW2DHT

**Comment by cjinhub** [comment]
> Hi Ian! Thanks for your answer. This is my test IGATE raw packet msg with the coordinates. The coordinates send by the Qsheng are ver far from reality, more than 100km.
> 
> 2024-02-27 17:08:34 -03: LW2DHT-3>APE32I,WIDE1-1,qAS,LW2DHT-1:/272008z3435.36S/05832.91W#/A=000003 Test Mode - Only Inet 2024-02-27 17:18:34 -03: LW2DHT-3>APE32I,WIDE1-1,qAS,LW2DHT-1:/272018z3435.36S/05832.91W#/A=000003 Test Mode - Only Inet
> 
> Thanks again for your time! You have done and doing a great job with this. Very Appreciated, Regards Mariano LW2DHT
APE32I seems like a "not K5" device. it should be APK5C1.

**Comment by 6h49af** [comment]
> Hi Ian! Thanks for your answer. This is my test IGATE raw packet msg with the coordinates. The coordinates send by the Qsheng are ver far from reality, more than 100km.
> 
> 2024-02-27 17:08:34 -03: LW2DHT-3>APE32I,WIDE1-1,qAS,LW2DHT-1:/272008z3435.36S/05832.91W#/A=000003 Test Mode - Only Inet 2024-02-27 17:18:34 -03: LW2DHT-3>APE32I,WIDE1-1,qAS,LW2DHT-1:/272018z3435.36S/05832.91W#/A=000003 Test Mode - Only Inet
> 
> Thanks again for your time! You have done and doing a great job with this. Very Appreciated, Regards Mariano LW2DHT

i see, maybe diffrent map takes diffrent coordinate system.

**Comment by DL8LDN** [comment]
My coordinates pick up from Google Maps.
73 de DL8LDN

![IMG_0093](https://github.com/phdlee/uvk5cec/assets/102428931/e41201d1-1d48-4833-af2b-2c369ea3ccf9)
![IMG_0092](https://github.com/phdlee/uvk5cec/assets/102428931/879f38df-e5d2-4ca1-b167-e6336ca80369)

**Comment by sq2mo** [comment]
It seems to be a bug, revealing itself if decimal part of the position is more than 4 digits.

**Comment by DL8LDN** [comment]
> It seems to be a bug, revealing itself if decimal part of the position is more than 4 digits.

Thank you, that was it and it worked for me 
73 de DL8LDN

**Comment by mariano80** [comment]
> It seems to be a bug, revealing itself if decimal part of the position is more than 4 digits.

Thanks SQ2MO for your suggetion. For me worked Ok!

**Comment by mariano80** [comment]
Only 4 digit are accepted before decimal point.
