### ISSUE TITLE
UV-K5 DigiManager 0.5 Not connecting

### ISSUE THREAD

**Issue by mariano80** [phdlee/uvk5cec#43]
Hi! I having trouble connecting de soft with the UV-K5. When I click connect i receive an error msg. 

![image](https://github.com/phdlee/uvk5cec/assets/26579010/91c6153c-473d-4f1f-8bc7-209e43bedcc5)

************** Texto de la excepción **************
System.IO.IOException: Uno de los dispositivos conectados al sistema no funciona.

   en System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
   en System.IO.Ports.SerialStream.InitializeDCB(Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Boolean discardNull)
   en System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   en System.IO.Ports.SerialPort.Open()
   en udpReceiver.frmUDPRecv.btnConnect_Click(Object sender, EventArgs e)
   en System.Windows.Forms.Control.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   en System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.ButtonBase.WndProc(Message& m)
   en System.Windows.Forms.Button.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by DL8LDN** [comment]
In my case I can connect to the comport but transfer not possible even i I have DIG+ and reboot the radio.
I am using a cable with profilic chip
73 de DL8LDN

**Comment by phdlee** [comment]
Tnx for trying this version
Check if Comport is being used by another program (for example, a firmware
download program, etc.).
Comport can only be opened by one program.
ian kd8cec

**Comment by phdlee** [comment]
Is it the same as the previous APRS message transmission test?
The frequency is entered on the APRS MSG channel, right?
Everything only works on the main screen.
Can't you save WSPR data?
I'll test it a few times and if it doesn't work, I'll add a testable
feature.

**Comment by DL8LDN** [comment]
Thanks for replying, I cannot save WSPR data and transfer APRS data with UV K5 DigiManager and yes QRG is in APRS MSG channel.

**Comment by mariano80** [comment]
Hi! Before several PC reboot now program works ok. But the same problem as DL8LDN. I open Port, but when I send Transfer, nothing happens on Uv-K5.

Regards and thanks for your replay!

**Comment by phdlee** [comment]
Thank you for testing.
Among the radios I own, I found one that had the same symptoms as you.
It seems that high-speed data transmission and reception is not smooth due
to some additions made while upgrading from Version B to Version C.
Tomorrow, based on radios with the same symptoms as yours, I will reduce
the speed or eliminate anything that is causing communication problems.
Please wait one day. I will update after solved.
Ian KD8CEC

**Comment by phdlee** [comment]
Thank you for testing.
Among the radios I own, I found one that had the same symptoms as you.
It seems that high-speed data transmission and reception is not smooth due
to some additions made while upgrading from Version B to Version C.
Tomorrow, based on radios with the same symptoms as yours, I will reduce
the speed or eliminate anything that is causing communication problems.
Please wait one day. I will update after solved.
Ian KD8CEC

**Comment by mariano80** [comment]
No problem! If you need more feedback, tell me.

Regards!

**Comment by phdlee** [comment]
The problem seems to have been resolved. Please test. (uploaded version
0.3D)
I brought the problematic laptop, UV-5K, and programming cable to a place
where the problem did not occur and compared them one by one.
The problem was with the USB to UART chip used in the programming cable. So
it seems that the problem only occurred to people under certain conditions.
So I lowered the speed to 57600 and confirmed stable transmission and
reception on all cables I have.

Ian KD8CEC

**Comment by phdlee** [comment]
The problem seems to have been resolved. Please test. (uploaded version
0.3D)
I brought the problematic laptop, UV-5K, and programming cable to a place
where the problem did not occur and compared them one by one.
The problem was with the USB to UART chip used in the programming cable. So
it seems that the problem only occurred to people under certain conditions.
So I lowered the speed to 57600 and confirmed stable transmission and
reception on all cables I have.

Ian KD8CEC

**Comment by N7SIX** [comment]
After Installing 0.3DB, I cannot save or transfer data from PC to K5 using my programming cable and DigiManager.

**Comment by phdlee** [comment]
You will also need to download DigiManager again.
Speed changed to 57600. Sorry for not explaining it.
As the 0.3DB acceleration became 57600, DigiManager was also set to 57600
by default.
Digimanager is 0.7.

Ian

**Comment by N7SIX** [comment]
Oh, I apologize, I didn't realize that the DigiManager had been updated as well.

Thank you!
73
Sean, N7SIX

**Comment by mariano80** [comment]
Hi Ian!

Well I updated the uv-k5 fw and the Digimanager. When I connected for the first time It works great and send packet over the air. But when I try again, sometimes the app freeze or I got an exeption again. The only way to correct it is extract usb cable and close the app. Connect again and start the app.

I'l try to mmake more test to give your a  better feedback. Thanks for your patience and work!

cec_0.3DB.packed.bin  <-- I'm using this fw

Edit: Seems that the COM port became busy for the second time or more. The only way for Tx again is disconnecting the cable. 

Regards
Mariano
LW2DHT

**Comment by phdlee** [comment]
Excellent
That probably appears to be a USB cable problem with RFI
Higher frequencies cause problems for computers. The test method is to
press PTT while connected to a computer. You'll probably run into the same
problem.
There are several solutions on the Internet
1. Do not use a USB hub and connect using a cable as short as possible.
2. Keep the radio's antenna away from the computer.
3. Install a core to prevent RFI in the USB cable.

Ian KD8CEC

**Comment by DL8LDN** [comment]
Thank you now is all working like aspected
73

**Comment by mariano80** [comment]
Ian! Thats correct!

In my case I used a usb 3.0 hub and works great. The problem was with the front usb port of computer. 

Well If for me it is ok and for DL8DLN. I close the Issue.

Regards Ian
Have a great weekend
LW2DHT

**Comment by mariano80** [comment]
Closed! Using a usb 3.0 hub worked for me. But the main problem is RF on Serial/USB.
