### ISSUE TITLE
WSPR not decoding in WSJT-X

### ISSUE THREAD

**Issue by tristanmoney** [phdlee/uvk5cec#45]
I'm trying to test the new WSPR function on 2m and have only had one transmission successfully demodulated by WSJT-X. I'm receiving the signal using a SDR in my garage, which is a proven setup for other experiments.

There appears to be some frequency drift - I wonder if this is causing issues with demodulation. I have tried various gain and volume settings with no improvement. Are others experiencing similar issues?

![image](https://github.com/phdlee/uvk5cec/assets/54490270/ba02eedb-9b9e-4ab5-86b2-fa75703c160e)

**Comment by phdlee** [comment]
First of all, congratulations on your one-time decoding.
1.WSPR at 2M requires both transmission and reception to be stable.
Frequencies are multiplied, so higher frequencies produce drift.
  For reference, my old device IC-706 cannot receive 2M WSPR. However,
FT-817, FT-857, etc. can be received.
2.If you are too close, the signal may be too loud. When testing at close
range, try using the minimum output. If you have a dummy load, try
connecting the dummy load.
Ian KD8CEC

**Comment by tristanmoney** [comment]
I tried a dummy load and also receiving using another UV-K5(8) and an AIOC for audio interface instead of the SDR. Unfortunately still no transmissions showing up in WSJT-X. Also tried a different UV-K5(8) for transmit but no change. 

I will continue testing when I have more time.

**Comment by tristanmoney** [comment]
With a dummy load on the UV-K5(8) I turned the SDR gain down all the way and got a nice thin signal in WSJT-X but it still didn't decode: 
![image](https://github.com/phdlee/uvk5cec/assets/54490270/f9384d58-98e1-4174-b062-57c6037e061d)

**Comment by tristanmoney** [comment]
It works reliably now - I guess the tone needs to be between 1400 and 1600 Hz to be decoded. I was trying 700, 400, and 1000 Hz but those won't work! I will try it out at a distance with an antenna tomorrow. 
![image](https://github.com/phdlee/uvk5cec/assets/54490270/7cf9b1e2-2579-4226-8615-9726acc5de22)
