### ISSUE TITLE
WSPR Testing

### ISSUE THREAD

**Issue by tristanmoney** [phdlee/uvk5cec#46]
Just tested 2m WSPR from 43 km away with good results. All 4 transmissions were received by my home station (VE7TMX is me). I used the stock antenna and placed the radio in the middle of my car's roof. I'm sure it will go much further with a better antenna, but even with the stock one it works very well.

The 1500 Hz tone is a bit unstable but still works with WSJT-X. Is the instability due to the lack of a crystal oscillator on the microcontroller?

For a CAD $28 radio it is amazing that it can even do WSPR. Great work @phdlee! I will keep testing.

![image](https://github.com/phdlee/uvk5cec/assets/54490270/7824f3ce-14ff-4692-b5d6-7feae636b968)

**Comment by phdlee** [comment]
That's great news.
Perhaps they can be transmitted further afield in the same environment
depending on the season.
And WSPR and FT8 do not depend on the MCU's clock. (using SI4819 Clock)
At higher frequencies (VHF, UHF) the frequency is not stable. This also
applies to Kenwood and I-com radios.
so, The WSJT-X program also includes a function to correct for slight
frequency shifting.

I have created WSJT-X programs on several radios and the UV-K5 has been
quite stable.
Perhaps it would be a little more stable if the temperature or radio was
turned on and there was a little waiting time.

Thanks for reporting.
PS: I plan to make a filter for 6M and install a simple amplifier circuit
on UV-K5 to transmit WSPR on 6M soon.

Ian KD8CEC
