### ISSUE TITLE
11m - change to FM problem (CEC 0.41 HF)

### ISSUE THREAD

**Issue by radonslide** [phdlee/uvk5cec#49]
If I want to switch to FM on the 11m band, the firmware throws me into the broadcast radio frequencies.
But FM modulation is the usual modulation on 11m in Europe.

**Comment by phdlee** [comment]
Unfortunately, SI4732-A10 does not support NBFM. Although NBFM is mentioned
in some documentation, it does not apply in the format we want.
So, if you need FM mode at 11m, you need to receive it from the main VFO,
not HF Receiver mode.
Ian KD8CEC

**Comment by radonslide** [comment]
Hello Ian. 
Thanks for your feedback on the subject. 
It was this mention in some documentation that made me undecided. 
Now I know how to handle this in FM CB. 
73 Michael

**Comment by radonslide** [comment]
Hello Ian.
Thanks for your feedback on the subject.
It was this mention in some documentation that made me undecided.
Now I know how to handle this in FM CB.
73 Michael
