### ISSUE TITLE
CEC 0.5 hf chirp load module

### ISSUE THREAD

**Issue by jepotter224** [phdlee/uvk5cec#57]
Hello, first thank you for developing a great firmware.! 

I purchased a UV-K6 with the HF mod and the CEC 0.5 hf installed. I found the
uvk5_CEC_05_HF_DO4KLA.py  python load module and put the 4-27-2024 
chirp version in developer mode, restarted chirp and loaded this python up.

When I attempt to download from the HT it get:
![Screenshot 2024-04-30 173027](https://github.com/phdlee/uvk5cec/assets/146049166/dd133955-0fea-4061-bdfa-277e1dde41c3)

Possibly you have run into this and can advise on steps to download and upload to the HT?

Thank you

**Comment by Stutzman4** [comment]
Where did you find the module for CHIRP I haven't been able to find it anywhere?

**Comment by jepotter224** [comment]
https://www.facebook.com/groups/961148971585971/files/files

**Comment by jepotter224** [comment]
https://git.okoyono.de/klaute/uvk5-cec-chirp-driver

**Comment by Stutzman4** [comment]
I found that this one will work with Chirp

https://www.facebook.com/groups/961148971585971/permalink/1175049783529221/

**Comment by jepotter224** [comment]
Thank you!

**Comment by reischle** [comment]
The code here [https://git.okoyono.de/klaute/uvk5-cec-chirp-driver](https://git.okoyono.de/klaute/uvk5-cec-chirp-driver) works without the error message, when you create a c:\tmp directory on your drive. (Assuming you run windows.) But as it is at the moment, the UI is rather confusing for me.
