### ISSUE TITLE
UVK5DigManager_v1.0.zip Detected as Virus

### ISSUE THREAD

**Issue by tristanmoney** [phdlee/uvk5cec#70]
Maybe a false positive but Windows Defender really doesn't like this file:
![image](https://github.com/phdlee/uvk5cec/assets/54490270/27634e1e-006f-45c3-8633-3ebec21f6b5d)

![image](https://github.com/phdlee/uvk5cec/assets/54490270/b7750998-d8bd-4304-aa4e-7cd4fa7f3cd3)

**Comment by n0th1n6** [comment]
I can confirm this.

**Comment by phdlee** [comment]
Ok thanks for information
I will check it tomorow because i stay other country now.

2024년 6월 17일 (월) 오후 1:02, Noli Rafallo ***@***.***>님이 작성:

**Comment by phdlee** [comment]
I verified the file on the virus total site.
Most Virus Check programs around the world determined that there was no
virus.
DigiManager receives UDP data from Wsjt-X. There are times when programs
that listen to sockets are mistaken for viruses.

The picture below shows the virus total result.

Ian KD8CEC

[image: image.png]

[image: image.png]


[image: image.png]

**Comment by n0th1n6** [comment]
It is weird, now it is not flagged as virus. The udpReceiver is used by wsjtx-2.6.1-win64_forUVK5?

![image](https://github.com/phdlee/uvk5cec/assets/5079634/40d30665-d2e9-4b87-b2b7-34fe7e558c3f)

**Comment by tristanmoney** [comment]
Very strange, it is no longer detected as a virus for me either. Windows Defender Security Intelligence updated today (June 19) so that must have resolved the false positive.

**Comment by tristanmoney** [comment]
Very strange, it is no longer detected as a virus for me either. Windows Defender Security Intelligence updated today (June 19) so that must have resolved the false positive.
