### ISSUE TITLE
CEC 0.51 freezes on wait

### ISSUE THREAD

**Issue by stevesalko** [phdlee/uvk5cec#71]
When I hold the 0 button it shows Wait and then freezes, I checked the connections and everything is connected correctly.

**Comment by AngelouDi** [comment]
How did you solve this? I am facing the same issue (regardless fw version). 2.5V board.

**Comment by stevesalko** [comment]
no, it was a faulty board, I ordered a new one and it did work, but after a while it also stopped working, ultimately gave up on it and soldered back the removed components.

**Comment by AngelouDi** [comment]
Which version was yours?
